# Generated by Django 5.2.4 on 2025-07-28 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entertainment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('min_height', models.CharField(max_length=50, verbose_name='Минимальный рост')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='park.park', verbose_name='Парк')),
            ],
        ),
    ]
