# Generated by Django 5.2.4 on 2025-08-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0002_entertainment'),
    ]

    operations = [
        migrations.AddField(
            model_name='park',
            name='main_photo',
            field=models.ImageField(blank=True, null=True, upload_to='parks/', verbose_name='Главное фото'),
        ),
    ]
