# Generated by Django 5.2.4 on 2025-08-29 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0003_park_main_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntertainmentPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='entertainments/', verbose_name='Фотографии развлечений')),
                ('entertainment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='park.entertainment', verbose_name='Развлечение')),
            ],
        ),
    ]
